sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
before_script:
after_success:
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
services:
  - mongodb
  - redis
  - riak
  - cassandra
  - neo4j
install:
  - npm list --depth=0
  - echo "CREATE KEYSPACE vixlet WITH REPLICATION = { 'class':'SimpleStrategy', 'replication_factor':1 };" | cqlsh
