sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.0-precise
    packages:
      - g++-4.8
      - mongodb-org-server
before_install:
  # install Neo4j locally:
  - wget dist.neo4j.org/neo4j-community-2.3.5-unix.tar.gz
  - tar -xzf neo4j-community-2.3.5-unix.tar.gz
  - neo4j-community-2.3.5/bin/neo4j start
  - "curl -H \"Content-Type: application/json\" -X POST -d '{\"password\":\"password\"}' -u neo4j:neo4j http://localhost:7474/user/neo4j/password"
  - "curl -H \"Content-Type: application/json\" -X GET -u neo4j:password http://localhost:7474/db/data/"
before_script:
after_success:
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
services:
install:
  - npm list --depth=0
